// commit-lint.js — shared, runtime-agnostic commit-message validation.
// Used by BOTH the git-native hook (hooks/git/commit-msg) and the optional
// agent-adapter early-warning (hooks/agent/branch-guard.js).
// Pure logic, no I/O, no process.exit — callers decide how to react.
//
// Rules (AGENTS.md, этап 5):
//   1. Conventional Commits: `<type>(<scope>)!: <subject>`
//   2. Без соавторства: запрет Co-Authored-By / Generated with … / 🤖 trailers.

const TYPES = [
  "feat", "fix", "docs", "style", "refactor", "perf", "test",
  "build", "ci", "chore", "revert", "improvement",
];
const TYPES_RE = TYPES.join("|");

// Conventional header — type is LOWERCASE (no `i` flag), optional scope, optional `!`.
//   feat(api)!: drop v1 support
const CONVENTIONAL_RE = new RegExp(
  `^(?:${TYPES_RE})(?:\\([a-z0-9._/-]+\\))?!?: .+`
);

// Auto-generated / special headers that git itself may produce — allowed as-is.
// (case-insensitive because git writes "Merge …"/"Revert …" capitalised)
const SPECIAL_RE = /^(?:merge\b|revert\b|release\b|fixup!|squash!)/i;

// Forbidden trailers (case-insensitive) — anything implying co-authorship / AI generation.
const FORBIDDEN_TRAILERS = [
  { re: /co-authored-by:/i, label: "Co-Authored-By trailer" },
  { re: /\bgenerated with\b/i, label: '"Generated with …"' },
  { re: /🤖/, label: "🤖 emoji" },
  {
    re: /generated[\s-]?by[\s:]+(?:claude|copilot|gpt|chatgpt|cursor|gemini|llama|codex|an?\s*(?:ai|llm))/i,
    label: '"Generated by <AI>"',
  },
  {
    re: /\b(?:written|created|authored)\s+by\s+(?:an?\s+)?(?:ai|llm|claude|gpt|copilot|cursor|gemini)\b/i,
    label: '"authored by <AI>"',
  },
];

// Strip git comment lines (`#…`) and everything after the verbose-diff scissors line,
// so we lint only the human-authored part of the message file.
function stripComments(raw) {
  const scissors = /^# -{4,} >8 -{4,}/m;
  let text = raw;
  const m = text.match(scissors);
  if (m) text = text.slice(0, m.index);
  return text
    .split(/\r?\n/)
    .filter((line) => !line.startsWith("#"))
    .join("\n")
    .trim();
}

// lint(raw) -> { ok, header, errors: [{code, message}] }
function lint(raw) {
  const msg = stripComments(String(raw || ""));
  const errors = [];
  const header = (msg.split(/\r?\n/)[0] || "").trim();

  if (!header) {
    errors.push({ code: "empty", message: "Пустое сообщение коммита." });
    return { ok: false, header, errors };
  }

  if (!CONVENTIONAL_RE.test(header) && !SPECIAL_RE.test(header)) {
    errors.push({
      code: "not-conventional",
      message:
        `Заголовок не conventional-commits.\n` +
        `   Было:      ${JSON.stringify(header)}\n` +
        `   Ожидается: <type>(<scope>): <subject>, type ∈ {${TYPES.join(", ")}}\n` +
        `   Пример:    feat(api): add /v2 endpoint   |   fix(parser): handle EOF`,
    });
  }

  for (const t of FORBIDDEN_TRAILERS) {
    if (t.re.test(msg)) {
      errors.push({
        code: "forbidden-trailer",
        message:
          `Найден запрещённый trailer (политика «без соавторства»): ${t.label}.\n` +
          `   Убери Co-Authored-By / Generated with / 🤖 из сообщения коммита.`,
      });
    }
  }

  return { ok: errors.length === 0, header, errors };
}

module.exports = { lint, stripComments, TYPES, CONVENTIONAL_RE, SPECIAL_RE, FORBIDDEN_TRAILERS };
